"""add server defaults

Revision ID: f3fbe153011a
Revises: e0110d70ec34
Create Date: 2026-08-22 11:34:10.448952

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f3fbe153011a"
down_revision: Union[str, Sequence[str], None] = "e0110d70ec34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("habits", "target_days", server_default=sa.text("21"))
    op.alter_column("habits", "completed_count", server_default=sa.text("0"))
    op.alter_column("habits", "is_active", server_default=sa.text("true"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("habits", "target_days", server_default=None)
    op.alter_column("habits", "completed_count", server_default=None)
    op.alter_column("habits", "is_active", server_default=None)
    # ### end Alembic commands ###
